# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    url: research
    weight: 10
  - name: Team
    url: team
    weight: 20    
  - name: Publications
    url: publications
    weight: 30
  - name: Software
    url: software
    weight: 40
  - name: News
    url: post
    weight: 50
  - name: Events
    url: events
    weight: 60
  - name: Join us
    url: vacancy
    weight: 70
  - name: Contact
    url: contact
    weight: 80
